apiVersion: v1
kind: Pod
metadata:
  name: sleeper-pod
  labels:
    app: sleeper
spec:
  containers:
    - name: sleeper-cn
      image: robsonlab.azurecr.io/sleeper:latest
      command:
        - "/bin/bash"
        - "/app/sleeper.sh"
      args:
        - "100"