apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-secret
spec:
  template:
    metadata:
     name: web-secret-pod
     labels:
      app: web-secret
    spec:
     containers:
      - name: web-secret-ct
        image: robsonlab.azurecr.io/ubuntu-web:v1.1
        ports:
         - containerPort: 8080
        args: [ "--color","red"]
        envFrom:
         - secretRef:
            name: app-config
  replicas: 3
  selector:
   matchLabels:
    app: web-secret
