apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dp-webapp-backend-v2
  name: webapp-backend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: dp-webapp-backend-v2
status:
  loadBalancer: {}
