apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dp-secrets-env
  name: dp-secrets-env
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dp-secrets-env
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dp-secrets-env
    spec:
      containers:
      - image: robsonlab.azurecr.io/webapp-secrets:latest
        name: webapp-secrets
        ports:
        - containerPort: 8080
        envFrom:
         - secretRef:
             name: webapp
status: {}
