apiVersion: v1
kind: Pod
metadata:
  name: pod-single-env-cm
spec:
  containers:
    - name: pod-sinle-env-cm-container
      image: robsonlab.azurecr.io/ubuntu-web:v1.1
      ports:
        - containerPort: 8080
      args: ["--color","pink"]
      env:
        - name: USERNAME
          valueFrom:
            configMapKeyRef:
              name: my-config-map
              key: USERNAME