apiVersion: v1
kind: Pod
metadata:
  name: sl
spec:
  containers:
    - name: sleep-01
      image: robsonlab.azurecr.io/sleep:v5
      command: ["python","app.py"]
      args:
        - "--seconds"
        - "120"
      