apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dp01
  namespace: dev
  labels:
   type: dep
spec:
  template:
    metadata:
     name: myapp-pod
     labels:
      app: web01
      tier: front-end
    spec:
     containers:
      - name: nginx-container
        image: nginx
  replicas: 3
  selector:
   matchLabels:
    app: web01

