apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dp-webapp-guaranteed
  name: dp-webapp-guaranteed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dp-webapp-guaranteed
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dp-webapp-guaranteed
    spec:
      containers:
      - image: robsonlab.azurecr.io/webapp-frontend:v2
        name: webapp-frontend
        ports:
        - containerPort: 3000
        resources:
         requests:
          cpu: 2
          memory: "1.5Gi"
         limits:
          cpu: 2
          memory: "1.5Gi"
status: {}
