apiVersion: v1
kind: LimitRange
metadata:
    name: limits
    namespace: best-effort
spec:
   limits:
    - max:
       cpu: "3"
       memory: 1Gi
      min:
       cpu: 50m
       memory: 100Mi
      type: Container
