apiVersion: v1
kind: LimitRange
metadata:
  name: limits
  namespace: best-effort
spec:
  limits:
   - default:
      cpu: 3
      memory: 1Gi
     defaultRequest:
      cpu: 100m
      memory: 500Mi
     min:
      cpu: 50m
      memory: 100Mi
     max: 
       cpu: 3
       memory: 1Gi
     type: Container
