apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-resource
  name: nginx-resource
  namespace: best-effort
spec:
  containers:
  - image: nginx
    name: nginx-resource
    resources:
     limits:
      cpu: "100m"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
