apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-cpu
  name: nginx-cpu
  namespace: best-effort
spec:
  containers:
  - image: nginx
    name: nginx-cpu
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
