apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-cpu-3
  name: nginx-cpu-3
  namespace: best-effort
spec:
  containers:
  - image: nginx
    name: nginx-cpu-3
    resources: 
      requests:
        cpu: 2.8
        memory: 400Mi
         
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
