apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dp-color-cm-single
  name: dp-color-cm-single
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dp-color-cm-single
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dp-color-cm-single
    spec:
      containers:
      - command:
        - python
        - app.py
        image: robsonlab.azurecr.io/webapp-color:latest
        name: webapp-color
        ports:
        - containerPort: 8080
        env:
         - name: APP_COLOR
           valueFrom:
            configMapKeyRef:
              name: cm-color-single
              key: APP_COLOR

