apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mytest
  name: mytest
  namespace: best-effort
spec:
  containers:
  - image: robsonlab.azurecr.io/webapp-liveness:latest
    name: mytest
    resources: 
      requests:
        cpu: 100m
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
