apiVersion: v1
kind: Pod
metadata:
  namespace: liveness
  creationTimestamp: null
  labels:
    run: webapp-02
    app: liveness  
  name: webapp-02
spec:
  containers:
  - image: robsonlab.azurecr.io/webapp-liveness:v3
    name: webapp-02
    ports:
    - containerPort: 8080
    resources: {}
    env:
     - name: APP_START_DELAY
       value: "80"
    readinessProbe:
      httpGet:
        path: /ready
        port: 8080     
      initialDelaySeconds: 80
      periodSeconds: 30
    livenessProbe:
      httpGet:
       path: /live
       port: 8080
      initialDelaySeconds: 80
      periodSeconds: 1    
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
