apiVersion: v1
kind: Service
metadata:
  namespace: liveness
  creationTimestamp: null
  labels:
    app: liveness
    run: webapp-01
  name: webapp-01
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: liveness
status:
  loadBalancer: {}
