apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dp-webapp-backend
  name: webapp-backend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: dp-webapp-backend
status:
  loadBalancer: {}
