apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc
  labels:
    app: my-rc-app
    type: front-end
spec:
  template:
    metadata:
      name: my-app-rc
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-rc
          image: nginx
  replicas: 3
