apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rs
  labels:
    type: ReplicaSet
spec:
  template:
    metadata:
      name: my-rs-app
      labels:
        app: my-rs-app
    spec:
      containers:
        - name: my-rs-app-cn
          image: nginx
  replicas: 15
  selector:
    matchLabels:
      app: my-rs-app
