apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dp-01
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec: 
      containers:
        - name: nginx
          image: nginx
          ports:
            - name: http
              containerPort: 80
  selector:
    matchLabels:
      app: nginx
