apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc
  labels:
    type: replication-controller
spec:
  replicas: 2
  template:
    metadata:
      name: my-rc-pod
      labels: 
        app: app01
    spec:
      containers:
        - name: my-rc-cn
          image: nginx