FROM python:3.10-alpine
RUN pip install psycopg2-binary
RUN pip install flask
RUN adduser --disabled-password --gecos '' webapp
COPY . /app
EXPOSE 8080
WORKDIR /app
USER webapp
ENTRYPOINT ["python","main.py"]

