apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: affinity-preferred
  name: affinity-preferred
spec:
  replicas: 2
  selector:
    matchLabels:
      app: affinity-preferred
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: affinity-preferred
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:  
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - awx
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
